// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoriaWEBAPI.Data;

namespace MonitoriaWEBAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220513034524_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonitoriaWEBAPI.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("client_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBorn")
                        .HasColumnType("DATE")
                        .HasColumnName("date_of_born");

                    b.Property<string>("NameAndSurname")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("name_and_surname");

                    b.Property<string>("RegisterOfPhysicalPerson")
                        .HasColumnType("CHAR(11)")
                        .HasColumnName("register_of_physical_person");

                    b.HasKey("ClientId");

                    b.ToTable("clients");
                });
#pragma warning restore 612, 618
        }
    }
}
