// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoriaWEBAPI.Data;

#nullable disable

namespace MonitoriaWEBAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220812203337_FirstMigrationWithMySql")]
    partial class FirstMigrationWithMySql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MonitoriaWEBAPI.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBorn")
                        .HasColumnType("DATE")
                        .HasColumnName("date_of_born");

                    b.Property<string>("Genre")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("genre");

                    b.Property<string>("NameAndSurname")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("name_and_surname");

                    b.Property<string>("RegisterOfPhysicalPerson")
                        .HasColumnType("CHAR(11)")
                        .HasColumnName("register_of_physical_person");

                    b.HasKey("ClientId")
                        .HasName("id");

                    b.ToTable("Tab_Clients", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
